package com.chamberly.chamberly.models

import com.google.firebase.firestore.FieldValue

data class Chamber(
    var AuthorName: String = "", // Display name of the chamber author (retrieved from cache)
    var AuthorUID: String = "", // UID of the chamber author (retrieved from cache)
    var blockedUsers: List<String> = listOf(), // Empty array of blocked users
    var forPool: Boolean = false, // Set to false
    var groupChatId: String = "", // DocumentID generated by Firestore
    var groupTitle: String = "", // Chamber title entered by the user
    val isLocked: Boolean = false,
    val topicId: String = "",
    val members: List<String> = emptyList(),
    val membersLimit: Int = 2, // Set to 2
    var publishedPool: Boolean = true, // Set to true
    var lastMessage: String = "", // To store the last message of the chat
    val timestamp: Any = FieldValue.serverTimestamp() // Timestamp of chamber creation
)

fun Chamber.toMap(): HashMap<String, Any> {
    return hashMapOf(
        "AuthorName" to AuthorName,
        "AuthorUID" to AuthorUID,
        "blockedUsers" to blockedUsers,
        "forPool" to forPool,
        "groupChatId" to groupChatId,
        "groupTitle" to groupTitle,
        "isLocked" to isLocked,
        "membersLimit" to membersLimit,
        "publishedPool" to publishedPool,
        "timestamp" to timestamp
    )
}

